# Generated by Django 3.2.9 on 2021-11-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=200, null=True)),
                ('NoOFOpenings', models.CharField(blank=True, max_length=200, null=True)),
                ('workfromHome', models.BooleanField(blank=True, default=False, null=True)),
                ('SkillsRequirement', models.CharField(max_length=1000, null=True)),
                ('LocationCity', models.CharField(blank=True, max_length=500, null=True)),
                ('EducationQualification', models.CharField(blank=True, max_length=500, null=True)),
                ('EnglishLevel', models.CharField(blank=True, max_length=500, null=True)),
                ('Experience', models.CharField(blank=True, max_length=500, null=True)),
                ('desc1', models.TextField(blank=True, null=True)),
                ('Timings', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkingDays', models.CharField(blank=True, max_length=500, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=500, null=True)),
                ('qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('yearofpassing', models.CharField(blank=True, max_length=500, null=True)),
                ('HigherEducation', models.CharField(blank=True, max_length=500, null=True)),
                ('Emailid', models.EmailField(blank=True, max_length=500, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='')),
                ('form_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slidename', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('SlideTitle', models.CharField(blank=True, max_length=500, null=True)),
                ('SlideDesc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
