# Generated by Django 3.2.9 on 2021-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc_app', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
